name: Build and Test Generation
on:
  push:
    branches:
      - ci
  schedule:
    - cron: 0 16 * * *
  workflow_dispatch:
    inputs:
      test:
        description: No need

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          ref: ci
          fetch-depth: 0
      - name: Merge from Azure/autorest.java
        env:
          SECRET: ${{ secrets.PERSONAL_TOKEN }}
        run: |
          git config --global user.email "tanchen@microsoft.com"
          git config --global user.name "Tanyi Chen"
          git pull --rebase=false --no-edit https://github.com/azure/autorest.java v4
          git push https://${SECRET}@github.com/chentanyi/autorest.java HEAD:ci

      - name: Cache maven dependencies
        uses: actions/cache@v1
        with:
          path: ~/.m2/repository
          key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
          restore-keys: |
            ${{ runner.os }}-maven-
            ${{ runner.os }}-

      - name: Setup node 14.x
        uses: actions/setup-node@v1
        with:
          node-version: '14.x'
      - name: 'Install autorest'
        run: |
          npm install -g autorest
          npm install
      - name: Setup jdk 1.11
        uses: actions/setup-java@v1
        with:
          java-version: 1.11
      - name: Build and Package
        run: mvn -f pom.xml -Dlocal package
      - name: clone azure-sdk-for-java
        run: git clone --depth 1 https://github.com/azure/azure-sdk-for-java
      - name: Install sdk-build-tools
        run: mvn -f azure-sdk-for-java/eng/code-quality-reports/pom.xml install
      - name: Generate and Compile
        run: |
          ./gen.py -u . -o azure-sdk-for-java