name: Build and Test Generation for All RPs
on:
  schedule:
    - cron: 0 18 * * *
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          ref: ci
          fetch-depth: 0
#      - name: Merge from Azure/autorest.java
#        run: |
#          git config --global user.email "actions@github.com"
#          git config --global user.name "Github Actions"
#          git pull --rebase=false --no-edit https://github.com/azure/autorest.java v4

      - name: Cache maven dependencies
        uses: actions/cache@v1
        with:
          path: ~/.m2/repository
          key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
          restore-keys: |
            ${{ runner.os }}-maven-
            ${{ runner.os }}-

      - name: Setup node 14.x
        uses: actions/setup-node@v1
        with:
          node-version: '14.x'
      - name: 'Install autorest'
        run: |
          npm install -g autorest
          npm install
      - name: Setup jdk 1.11
        uses: actions/setup-java@v1
        with:
          java-version: 1.11
      - name: Build and Package
        run: mvn -f pom.xml -P local package
      - name: clone azure-rest-api-specs
        run: git clone --depth 1 https://github.com/azure/azure-rest-api-specs
      - name: Generate and Compile
        run: |
          ./gen_all.py -u . -s ./azure-rest-api-specs
